### ISSUE TITLE
Full test results.

### ISSUE THREAD

**Issue by AsaAyers** [johanneswuerbach/saucie#24]
I'm using saucie through [testem](https://github.com/airportyh/testem) to run [tape](https://github.com/substack/tape/) tests on SauceLabs.

Using my workaround in https://github.com/johanneswuerbach/saucie/issues/5#issuecomment-147855384 I have been able to make my tests run and provide a pass/fail. When this runs I just have a pass/fail for the whole browser:

```
ok 1 SL_Chrome - https://saucelabs.com/jobs/...
ok 2 SL_IE_11 - https://saucelabs.com/jobs/...

1..2
# tests 2
# pass  2
# fail  0

# ok
```

Is there any way to get this to report the actual tests?

**Comment by johanneswuerbach** [comment]
I'm not sure whether this works with tape, but for qunit & mocha this launcher in your `testem.json` allows printing results of all your tests:

```json
"launchers": {
 "SL_chrome": {
   "exe": "./node_modules/.bin/saucie",
   "args": [
     "-b", "chrome", "--at", "--u"
   ],
   "protocol": "browser"
 }
}
```

**Comment by AsaAyers** [comment]
If you can help point me to how saucie passes the results back to testem, I can help make it work with the `tap` protocol. Maybe I'm missing something, but it seems like it only cares about `passed` or `failedCount` https://github.com/johanneswuerbach/saucie/blob/master/lib/sauce-update-job-status.js#L34-L39

**Comment by johanneswuerbach** [comment]
Saucie isn't returning the results back to testem, but is actually collecting them itself when running with `protocol: browser`.

You can find a basic example here: https://github.com/airportyh/testem/blob/master/views/taprunner.mustache#L11-L16
