### ISSUE TITLE
Platform version is converted to number automatically

### ISSUE THREAD

**Issue by marcoow** [johanneswuerbach/saucie#58]
The platform version argument is always converted to a number (as long as it looks like a number as e.g. `5.1`). That's because of [this line](https://github.com/substack/minimist/blob/master/index.js#L59) in minimist which optimist depends on. Flagging arguments as strings actually doesn't work as the argument is flagged with its long name but the check is performed with the short name. This is actually [fixed in minimist](https://github.com/substack/minimist/blob/master/index.js#L31) but optimist (which is deprecated) depends on a very old version of it which doesn't include that change.

I'd suggest switching from optimist to minimist. I'd be happy to prepare a PR if there's consensus.

**Comment by johanneswuerbach** [comment]
Sounds good to me 👍

**Comment by marcoow** [comment]
minimist actually seems pretty unmaintained as well. Looks like commander is the most popular solution. Might make more sense to switch to that then?
