### ISSUE TITLE
"--no-ct" error

### ISSUE THREAD

**Issue by bjayepps** [johanneswuerbach/saucie#69]
![image](https://cloud.githubusercontent.com/assets/24317692/26462077/621ecede-414d-11e7-9151-599bc4c42c64.png)

**Comment by mccataldo** [comment]
same here

**Comment by johanneswuerbach** [comment]
Which version of saucie are you using, > 3 requires `--no-connect`

**Comment by bjayepps** [comment]
using saucie  3.1.0,   and renamed the option to --no--connect,  still have the same error.
